import React, { createContext, useContext, useState } from 'react';

export const LANGS = {
  EN: 'en',
  TA: 'ta',
  HI: 'hi',
};

export const translations = {
  en: {
    appName: 'AGRI-OPT',
    tagline: 'Intelligent Agricultural Management',
    loading: 'Initializing Agricultural Intelligence...',
    login: 'Login',
    register: 'Create Account',
    username: 'Username',
    userId: 'User ID',
    phone: 'Phone Number',
    countryCode: 'Country Code',
    password: 'Password',
    confirmPass: 'Confirm Password',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    otpEmail: 'Enter Email OTP',
    otpPhone: 'Enter Phone OTP',
    resendIn: 'Resend OTP in',
    resendOtp: 'Resend OTP',
    otpWrong: 'Wrong OTP! Timer running...',
    verified: 'Verified!',
    enterLand: 'Enter Land Details',
    landArea: 'Land Area',
    location: 'Location',
    openMap: 'Open Google Maps',
    useMyLocation: 'Use My Location',
    landLength: 'Land Length (ft)',
    landWidth: 'Land Width (ft)',
    plotType: 'Plot Type',
    rectangular: 'Rectangular',
    nonRectangular: 'Non-Rectangular',
    submit: 'Submit & Analyze',
    landType: 'Land Type',
    soilType: 'Soil Type',
    fieldSlope: 'Field Slope',
    fertilizer: 'Fertilizer Required',
    landSecurity: 'Land Security Status',
    cropSchedule: 'Crop & Plant Schedule',
    crop: 'Crop / Plant',
    fertilizerDaily: 'Fertilizer (Daily)',
    waterHourly: 'Water (Hourly)',
    grassMaint: 'Grass Maintenance',
    viewReport: 'View Full Report',
    aiAssistant: 'Agri AI Assistant',
    typeMessage: 'Ask about farming, crops, weather...',
    send: 'Send',
    temperature: 'Temperature',
    humidity: 'Humidity',
    weather: 'Weather',
    home: 'Home',
    analyze: 'Analyze',
    results: 'Results',
    logout: 'Logout',
    language: 'Language',
    speak: 'Speak',
    stopSpeak: 'Stop',
    sqFt: 'sq ft',
    cents: 'cents',
    guntas: 'guntas',
    acres: 'acres',
    floodRisk: 'Flood Risk & Protection',
    baseNPK: 'Base Fertilizer Required',
    groundWater: 'Ground Water Level',
    secure: 'Secure',
    encroachment: 'Encroachment Risk',
    noEncroachment: 'No Encroachment',
    reportReady: 'Report Ready',
    analyzing: 'Analyzing your land data...',
    email: 'Email Address',
    selectCountry: 'Select Country',
    male: 'Male',
    female: 'Female',
    gender: 'Gender',
    dob: 'Date of Birth',
    state: 'State',
    district: 'District',
    village: 'Village',
    selectedArea: 'Selected Area',
    area: 'Area',
    waterRetention: 'Water Retention',
    organicMatter: 'Organic Matter',
    drainage: 'Drainage',
    erosionRisk: 'Erosion Risk',
    irrigationMethod: 'Irrigation Method',
    bundNeeded: 'Bund Needed',
    baseTreatment: 'Base Treatment',
    microNutrients: 'Micro-nutrients',
    bioFertilizer: 'Bio-fertilizer',
    surveyNo: 'Survey No.',
    landUse: 'Land Use',
    season: 'Season',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    vLow: 'Very Low',
    vHigh: 'Very High',
    secure: 'Secure',
    modRisk: 'Moderate Risk',
    highRisk: 'High Risk',
    noEncroachment: 'No Encroachment Detected',
    boundaryVerify: 'Boundary verification recommended',
    surveyReq: 'Immediate survey required',
    mobile: 'Mobile',
    loc: 'Loc',
    yes: 'Yes',
    no: 'No',
    optional: 'Optional',
    mandatory: 'Mandatory',
    // Soil Types
    'Red Loamy Soil': 'Red Loamy Soil',
    'Black Cotton Soil': 'Black Cotton Soil',
    'Alluvial Soil': 'Alluvial Soil',
    'Laterite Soil': 'Laterite Soil',
    'Sandy Soil': 'Sandy Soil',
    'Clay Soil': 'Clay Soil',
    'Silt Soil': 'Silt Soil',
    // Crops
    'Paddy (Rice)': 'Paddy (Rice)',
    'Wheat': 'Wheat',
    'Sugarcane': 'Sugarcane',
    'Cotton': 'Cotton',
    'Tomato': 'Tomato',
    'Banana': 'Banana',
    'Mango': 'Mango',
    'Coconut': 'Coconut',
    'Groundnut': 'Groundnut',
    'Maize': 'Maize',
    'Onion': 'Onion',
    'Sunflower': 'Sunflower',
    'Soybean': 'Soybean',
    'Millets': 'Millets',
    // Maintenance
    'Weekly weeding': 'Weekly weeding',
    'Monthly trim': 'Monthly trim',
    'Bi-weekly clear': 'Bi-weekly clear',
    '2x monthly': '2x monthly',
    'Trim weekly': 'Trim weekly',
    'Clear 1m radius': 'Clear 1m radius',
    'Clear 2m radius': 'Clear 2m radius',
    'Bi-weekly': 'Bi-weekly',
    'Monthly': 'Monthly',
    // Seasons
    'Kharif/Rabi': 'Kharif/Rabi',
    'Kharif': 'Kharif',
    'Rabi': 'Rabi',
    'Annual': 'Annual',
    'All year': 'All year',
  },
  ta: {
    appName: 'அக்ரி-ஆப்ட்',
    tagline: 'நுண்ணிய விவசாய மேலாண்மை',
    loading: 'விவசாய நுண்ணிவு தொடங்குகிறது...',
    login: 'உள்நுழை',
    register: 'கணக்கு உருவாக்கு',
    username: 'பயனர் பெயர்',
    userId: 'பயனர் ஐடி',
    phone: 'தொலைபேசி எண்',
    countryCode: 'நாட்டு குறியீடு',
    password: 'கடவுச்சொல்',
    confirmPass: 'கடவுச்சொல் உறுதி',
    sendOtp: 'OTP அனுப்பு',
    verifyOtp: 'OTP சரிபார்',
    otpEmail: 'மின்னஞ்சல் OTP உள்ளிடு',
    otpPhone: 'தொலைபேசி OTP உள்ளிடு',
    resendIn: 'OTP மீண்டும் அனுப்பு',
    resendOtp: 'OTP மீண்டும் அனுப்பு',
    otpWrong: 'தவறான OTP! நேரம் ஓடுகிறது...',
    verified: 'சரிபார்க்கப்பட்டது!',
    enterLand: 'நில விவரங்கள் உள்ளிடு',
    landArea: 'நில பரப்பளவு',
    location: 'இருப்பிடம்',
    openMap: 'Google வரைபடம் திற',
    useMyLocation: 'என் இருப்பிடம் பயன்படுத்து',
    landLength: 'நில நீளம் (அடி)',
    landWidth: 'நில அகலம் (அடி)',
    plotType: 'நில வகை',
    rectangular: 'செவ்வக வடிவம்',
    nonRectangular: 'செவ்வக இல்லாத வடிவம்',
    submit: 'சமர்ப்பி & பகுப்பாய்வு',
    landType: 'நில வகை',
    soilType: 'மண் வகை',
    fieldSlope: 'வயல் சரிவு',
    fertilizer: 'தேவையான உரம்',
    landSecurity: 'நில பாதுகாப்பு நிலை',
    cropSchedule: 'பயிர் & தாவர அட்டவணை',
    crop: 'பயிர் / தாவரம்',
    fertilizerDaily: 'உரம் (தினசரி)',
    waterHourly: 'தண்ணீர் (மணிக்கு)',
    grassMaint: 'புல் பராமரிப்பு',
    viewReport: 'முழு அறிக்கை காண்',
    aiAssistant: 'அக்ரி AI உதவியாளர்',
    typeMessage: 'விவசாயம், பயிர்கள், வானிலை...',
    send: 'அனுப்பு',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    weather: 'வானிலை',
    home: 'முகப்பு',
    analyze: 'பகுப்பாய்வு',
    results: 'முடிவுகள்',
    logout: 'வெளியேறு',
    language: 'மொழி',
    speak: 'படி',
    stopSpeak: 'நிறுத்து',
    sqFt: 'சதுர அடி',
    cents: 'சென்ட்',
    guntas: 'குண்டா',
    acres: 'ஏக்கர்',
    floodRisk: 'வெள்ள அபாயம் & பாதுகாப்பு',
    baseNPK: 'அடிப்படை உரம் தேவை',
    groundWater: 'நிலத்தடி நீர் மட்டம்',
    secure: 'பாதுகாப்பானது',
    encroachment: 'ஆக்கிரமிப்பு அபாயம்',
    noEncroachment: 'ஆக்கிரமிப்பு இல்லை',
    reportReady: 'அறிக்கை தயார்',
    analyzing: 'உங்கள் நில தரவை பகுப்பாய்கிறது...',
    email: 'மின்னஞ்சல் முகவரி',
    selectCountry: 'நாடு தேர்ந்தெடு',
    male: 'ஆண்',
    female: 'பெண்',
    gender: 'பாலினம்',
    dob: 'பிறந்த தேதி',
    state: 'மாநிலம்',
    district: 'மாவட்டம்',
    village: 'கிராமம்',
    selectedArea: 'தேர்ந்தெடுக்கப்பட்ட பகுதி',
    area: 'பரப்பளவு',
    waterRetention: 'நீர் தக்கவைப்பு',
    organicMatter: 'கரிமப் பொருட்கள்',
    drainage: 'நீர் வடிகால்',
    erosionRisk: 'மண்ணரிப்பு அபாயம்',
    irrigationMethod: 'நீர்பாசன முறை',
    bundNeeded: 'வரப்பு தேவை',
    baseTreatment: 'அடிப்படை சிகிச்சை',
    microNutrients: 'நுண்ணூட்டச்சத்துக்கள்',
    bioFertilizer: 'உயிர் உரம்',
    surveyNo: 'சர்வே எண்',
    landUse: 'நில பயன்பாடு',
    season: 'பருவகாலம்',
    low: 'குறைவு',
    medium: 'நடுத்தரம்',
    high: 'அதிகம்',
    vLow: 'மிகக் குறைவு',
    vHigh: 'மிக அதிகம்',
    secure: 'பாதுகாப்பானது',
    modRisk: 'மிதமான அபாயம்',
    highRisk: 'அதிக அபாயம்',
    noEncroachment: 'ஆக்கிரமிப்பு எதுவும் கண்டறியப்படவில்லை',
    boundaryVerify: 'எல்லை சரிபார்ப்பு பரிந்துரைக்கப்படுகிறது',
    surveyReq: 'உடனடி சர்வே தேவை',
    mobile: 'கைபேசி',
    loc: 'இடம்',
    yes: 'ஆம்',
    no: 'இல்லை',
    optional: 'விருப்பமானது',
    mandatory: 'கட்டாயமானது',
    // Soil Types
    'Red Loamy Soil': 'செம்மண்',
    'Black Cotton Soil': 'கரிசல் மண்',
    'Alluvial Soil': 'வண்டல் மண்',
    'Laterite Soil': 'சரளை மண்',
    'Sandy Soil': 'மணல் மண்',
    'Clay Soil': 'களிமண்',
    'Silt Soil': 'வண்டல் மண்',
    // Crops
    'Paddy (Rice)': 'நெல் (அரிசி)',
    'Wheat': 'கோதுமை',
    'Sugarcane': 'கரும்பு',
    'Cotton': 'பருத்தி',
    'Tomato': 'தக்காளி',
    'Banana': 'வாழை',
    'Mango': 'மாம்பழம்',
    'Coconut': 'தென்னை',
    'Groundnut': 'நிலக்கடலை',
    'Maize': 'சோளம்',
    'Onion': 'வெங்காயம்',
    'Sunflower': 'சூரியகாந்தி',
    'Soybean': 'சோயாபீன்',
    'Millets': 'சிறுதானியங்கள்',
    // Maintenance
    'Weekly weeding': 'வாராந்திர களையெடுத்தல்',
    'Monthly trim': 'மாதாந்திர வெட்டுதல்',
    'Bi-weekly clear': 'இரு வாரங்களுக்கு ஒருமுறை சுத்தம் செய்தல்',
    '2x monthly': 'மாதத்திற்கு 2 முறை',
    'Trim weekly': 'வாராந்திர கத்தரித்தல்',
    'Clear 1m radius': '1மீ சுற்றளவை சுத்தம் செய்யவும்',
    'Clear 2m radius': '2மீ சுற்றளவை சுத்தம் செய்யவும்',
    'Bi-weekly': 'இரு வாரங்களுக்கு ஒருமுறை',
    'Monthly': 'மாதாந்திரம்',
    // Seasons
    'Kharif/Rabi': 'காரீஃப்/ரபி',
    'Kharif': 'காரீஃப்',
    'Rabi': 'ரபி',
    'Annual': 'வருடாந்திர',
    'All year': 'ஆண்டு முழுவதும்',
  },
  hi: {
    appName: 'अग्री-ऑप्ट',
    tagline: 'बुद्धिमान कृषि प्रबंधन',
    loading: 'कृषि बुद्धिमत्ता प्रारंभ हो रही है...',
    login: 'लॉगिन',
    register: 'खाता बनाएं',
    username: 'उपयोगकर्ता नाम',
    userId: 'उपयोगकर्ता आईडी',
    phone: 'फ़ोन नंबर',
    countryCode: 'देश कोड',
    password: 'पासवर्ड',
    confirmPass: 'पासवर्ड की पुष्टि',
    sendOtp: 'OTP भेजें',
    verifyOtp: 'OTP सत्यापित करें',
    otpEmail: 'ईमेल OTP दर्ज करें',
    otpPhone: 'फ़ोन OTP दर्ज करें',
    resendIn: 'OTP पुनः भेजें',
    resendOtp: 'OTP पुनः भेजें',
    otpWrong: 'गलत OTP! टाइमर चल रहा है...',
    verified: 'सत्यापित!',
    enterLand: 'भूमि विवरण दर्ज करें',
    landArea: 'भूमि क्षेत्र',
    location: 'स्थान',
    openMap: 'Google मानचित्र खोलें',
    useMyLocation: 'मेरा स्थान उपयोग करें',
    landLength: 'भूमि की लंबाई (फीट)',
    landWidth: 'भूमि की चौड़ाई (फीट)',
    plotType: 'भूखंड प्रकार',
    rectangular: 'आयताकार',
    nonRectangular: 'गैर-आयताकार',
    submit: 'जमा करें और विश्लेषण करें',
    landType: 'भूमि प्रकार',
    soilType: 'मिट्टी का प्रकार',
    fieldSlope: 'खेत की ढलान',
    fertilizer: 'आवश्यक उर्वरक',
    landSecurity: 'भूमि सुरक्षा स्थिति',
    cropSchedule: 'फसल और पौधे की अनुसूची',
    crop: 'फसल / पौधा',
    fertilizerDaily: 'उर्वरक (दैनिक)',
    waterHourly: 'पानी (प्रति घंटा)',
    grassMaint: 'घास की देखभाल',
    viewReport: 'पूरी रिपोर्ट देखें',
    aiAssistant: 'कृषि AI सहायक',
    typeMessage: 'खेती, फसलें, मौसम के बारे में पूछें...',
    send: 'भेजें',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    weather: 'मौसम',
    home: 'होम',
    analyze: 'विश्लेषण',
    results: 'परिणाम',
    logout: 'लॉगआउट',
    language: 'भाषा',
    speak: 'पढ़ें',
    stopSpeak: 'रोकें',
    sqFt: 'वर्ग फीट',
    cents: 'सेंट',
    guntas: 'गुंटा',
    acres: 'एकड़',
    floodRisk: 'बाढ़ जोखिम और सुरक्षा',
    baseNPK: 'आधार उर्वरक आवश्यक',
    groundWater: 'भूजल स्तर',
    secure: 'सुरक्षित',
    encroachment: 'अतिक्रमण जोखिम',
    noEncroachment: 'कोई अतिक्रमण नहीं',
    reportReady: 'रिपोर्ट तैयार',
    analyzing: 'आपकी भूमि डेटा का विश्लेषण...',
    email: 'ईमेल पता',
    selectCountry: 'देश चुनें',
    male: 'पुरुष',
    female: 'महिला',
    gender: 'लिंग',
    dob: 'जन्म तिथि',
    state: 'राज्य',
    district: 'जिला',
    village: 'गांव',
    selectedArea: 'चयनित क्षेत्र',
    area: 'क्षेत्रफल',
    waterRetention: 'जल प्रतिधारण',
    organicMatter: 'कार्बनिक पदार्थ',
    drainage: 'जल निकासी',
    erosionRisk: 'मृदा अपरदन जोखिम',
    irrigationMethod: 'सिंचाई विधि',
    bundNeeded: 'मेड़ की आवश्यकता',
    baseTreatment: 'आधार उपचार',
    microNutrients: 'सूक्ष्म पोषक तत्व',
    bioFertilizer: 'जैव उर्वरक',
    surveyNo: 'सर्वेक्षण संख्या',
    landUse: 'भूमि उपयोग',
    season: 'सीजन',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    vLow: 'बहुत कम',
    vHigh: 'बहुत उच्च',
    secure: 'सुरक्षित',
    modRisk: 'मध्यम जोखिम',
    highRisk: 'उच्च जोखिम',
    noEncroachment: 'कोई अतिक्रमण नहीं पाया गया',
    boundaryVerify: 'सीमा सत्यापन की सिफारिश की गई',
    surveyReq: 'तत्काल सर्वेक्षण आवश्यक',
    mobile: 'मोबाइल',
    loc: 'स्थान',
    yes: 'हाँ',
    no: 'नहीं',
    optional: 'वैकल्पिक',
    mandatory: 'अनिवार्य',
    // Soil Types
    'Red Loamy Soil': 'लाल दोमट मिट्टी',
    'Black Cotton Soil': 'काली कपास मिट्टी',
    'Alluvial Soil': 'जलोढ़ मिट्टी',
    'Laterite Soil': 'लेटराइट मिट्टी',
    'Sandy Soil': 'रेतीली मिट्टी',
    'Clay Soil': 'चिकनी मिट्टी',
    'Silt Soil': 'गाद मिट्टी',
    // Crops
    'Paddy (Rice)': 'धान (चावल)',
    'Wheat': 'गेहूं',
    'Sugarcane': 'गन्ना',
    'Cotton': 'कपास',
    'Tomato': 'टमाटर',
    'Banana': 'केला',
    'Mango': 'आम',
    'Coconut': 'नारियल',
    'Groundnut': 'मूंगफली',
    'Maize': 'मक्का',
    'Onion': 'प्याज',
    'Sunflower': 'सूरजमुखी',
    'Soybean': 'सोयाबीन',
    'Millets': 'बाजरा',
    // Maintenance
    'Weekly weeding': 'साप्ताहिक निराई',
    'Monthly trim': 'मासिक छँटाई',
    'Bi-weekly clear': 'पाक्षिक सफाई',
    '2x monthly': 'महीने में 2 बार',
    'Trim weekly': 'साप्ताहिक छँटाई',
    'Clear 1m radius': '1 मीटर त्रिज्या साफ करें',
    'Clear 2m radius': '2 मीटर त्रिज्या साफ करें',
    'Bi-weekly': 'पाक्षिक',
    'Monthly': 'मासिक',
    // Seasons
    'Kharif/Rabi': 'खरीफ/रबी',
    'Kharif': 'खरीफ',
    'Rabi': 'रबी',
    'Annual': 'वार्षिक',
    'All year': 'पूरे साल',
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(LANGS.EN);

  const t = (key) => translations[lang][key] || translations.en[key] || key;

  const speak = (text) => {
    if ('speechSynthesis' in window) {
      window.speechSynthesis.cancel();
      const utter = new SpeechSynthesisUtterance(text);
      utter.lang = lang === 'ta' ? 'ta-IN' : lang === 'hi' ? 'hi-IN' : 'en-IN';
      utter.rate = 0.9;
      window.speechSynthesis.speak(utter);
    }
  };

  const stopSpeak = () => {
    if ('speechSynthesis' in window) window.speechSynthesis.cancel();
  };

  const langClass = lang === 'ta' ? 'lang-ta' : lang === 'hi' ? 'lang-hi' : '';

  return (
    <LangContext.Provider value={{ lang, setLang, t, speak, stopSpeak, langClass }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
